import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '@/components/nav';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DashBoard App',
  description: 'Generated by create next app',
}

export default async function RootLayout ({ children }) {
  
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col justify-between min-h-screen`}>
          <header className=''><Nav/></header>
          <main className='mb-auto'>{children}</main>
          <footer className=''>
            <Footer/>
          </footer>
      </body>
    </html>
  );
}
